/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useFrame } from "@react-three/fiber";
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/kucing.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions["polySurface8|Take 001|BaseLayer"].play();
    actions["Cat_Eye_L|Take 001|BaseLayer"].play();
    actions["Cat_Eye_R|Take 001|BaseLayer"].play();
    actions["Cat_Mustache_1|Take 001|BaseLayer"].play();
    actions["Cat_Mustache_2|Take 001|BaseLayer"].play();
    actions["Cat_Mustache_3|Take 001|BaseLayer"].play();
    actions["Cat_Mustache_4|Take 001|BaseLayer"].play();
    actions["Cat_Tail|Take 001|BaseLayer"].play();
  })
  useFrame(()=>{
    var mesh = group.current
    // Gamau Kehujanan
    // mesh.rotation.set(0, 0.9, 0)
    // mesh.position.set(2.3, 3, 1.9)
    mesh.position.set(0, 1.2, 5.5)
    mesh.scale.set(8, 8, 8)
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="polySurface8" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform1" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <group name="Cat_Eye_L">
            <mesh name="Mesh002" geometry={nodes.Mesh002.geometry} material={materials.M_Cat_Yellow} />
            <mesh name="Mesh002_1" geometry={nodes.Mesh002_1.geometry} material={materials.M_Cat_Black} />
          </group>
          <group name="Cat_Eye_R">
            <mesh name="Mesh001" geometry={nodes.Mesh001.geometry} material={materials.M_Cat_Black} />
            <mesh name="Mesh001_1" geometry={nodes.Mesh001_1.geometry} material={materials.M_Cat_Yellow} />
          </group>
          <mesh name="Cat_Mustache_1" geometry={nodes.Cat_Mustache_1.geometry} material={materials.M_Cat_Body} />
          <mesh name="Cat_Mustache_2" geometry={nodes.Cat_Mustache_2.geometry} material={materials.M_Cat_Body} />
          <mesh name="Cat_Mustache_3" geometry={nodes.Cat_Mustache_3.geometry} material={materials.M_Cat_Body} />
          <mesh name="Cat_Mustache_4" geometry={nodes.Cat_Mustache_4.geometry} material={materials.M_Cat_Body} />
          <mesh name="Cat_Tail" geometry={nodes.Cat_Tail.geometry} material={materials.M_Cat_Body} position={[0.08, 0.09, -0.06]} rotation={[0, -0.01, -0.03]} />
          <group name="Cat_Body">
            <mesh name="Mesh008" geometry={nodes.Mesh008.geometry} material={materials.M_Cat_Pink} />
            <mesh name="Mesh008_1" geometry={nodes.Mesh008_1.geometry} material={materials.M_Cat_Body} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/kucing.glb')
